version: '3.7'

services:

  mongo:
    image: mongo

  cinematics:
    build: .
    image: registry.gitlab.com/ajtuss/cinematics
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongo

  cinematics-gui:
    image: registry.gitlab.com/ajtuss/cinematics-gui
    ports:
      - 80:80
    depends_on:
      - cinematics

  mongo-seed:
    build: ./src/main/docker/mongo-seed
    depends_on:
      - mongo
